### ISSUE TITLE
java.lang.StackOverflowError: stack size 8MB on line number 65

### ISSUE THREAD

**Issue by abhishekthanvi** [500px/500px-android-blur#23]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.example.user.designsample, PID: 19998
                                                                                    java.lang.StackOverflowError: stack size 8MB
                                                                                        at android.graphics.Canvas.drawOval(Canvas.java:1155)
                                                                                        at android.graphics.Canvas.drawOval(Canvas.java:1147)
                                                                                        at android.graphics.drawable.GradientDrawable.draw(GradientDrawable.java:615)
                                                                                        at android.view.View.drawBackground(View.java:16376)
                                                                                        at android.view.View.draw(View.java:16175)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundredpx.android.blur.BlurringView.onDraw(BlurringView.java:65)
                                                                                        at android.view.View.draw(View.java:16184)
                                                                                        at com.fivehundred
05-05 23:16:31.323 19998-19998/com.example.user.humandesignsample E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 6333780)
05-05 23:16:31.361 19998-19998/com.example.user.humandesignsample E/AndroidRuntime: Error reporting crash
                                                                                    android.os.TransactionTooLargeException: data parcel size 6333780 bytes
                                                                                        at android.os.BinderProxy.transactNative(Native Method)
                                                                                        at android.os.BinderProxy.transact(Binder.java:503)
                                                                                        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
                                                                                        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                                                        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by wedkarz** [comment]
I had such problem when my hierarchy contained Blurring view as child of blurred view. Try making blurring view and blurred view on the same level.

**Comment by BlacksmithVRS** [comment]
@wedkarz Thank you a lot! I was thinking this the wrong way. Putting the views on the same level worked like a charm!

**Comment by AtulDagur** [comment]
@wedkarz I have made a tictactoe when I use minimax ap crash and gives stackoverflow error
